/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class plugins_wlx_WLXPluginAdapter */

#ifndef _Included_plugins_wlx_WLXPluginAdapter
#define _Included_plugins_wlx_WLXPluginAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     plugins_wlx_WLXPluginAdapter
 * Method:    getHWND
 * Signature: (Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_plugins_wlx_WLXPluginAdapter_getHWND
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     plugins_wlx_WLXPluginAdapter
 * Method:    getHWND2
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_plugins_wlx_WLXPluginAdapter_getHWND2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     plugins_wlx_WLXPluginAdapter
 * Method:    setSize
 * Signature: (III)I
 */
JNIEXPORT void JNICALL Java_plugins_wlx_WLXPluginAdapter_setSize
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
