/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class plugins_wcx_WCXPluginAdapter */

#ifndef _Included_plugins_wcx_WCXPluginAdapter
#define _Included_plugins_wcx_WCXPluginAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     plugins_wcx_WCXPluginAdapter
 * Method:    packerSetChangeVol
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_plugins_wcx_WCXPluginAdapter_packerSetChangeVol
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     plugins_wcx_WCXPluginAdapter
 * Method:    packerSetProcessData
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_plugins_wcx_WCXPluginAdapter_packerSetProcessData
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
