/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class plugins_wfx_WFXPluginAdapter */

#ifndef _Included_plugins_wfx_WFXPluginAdapter
#define _Included_plugins_wfx_WFXPluginAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     plugins_wfx_WFXPluginAdapter
 * Method:    fsSetProgress
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_plugins_wfx_WFXPluginAdapter_fsSetProgress
  (JNIEnv *, jobject, jint, jstring, jstring, jint);

/*
 * Class:     plugins_wfx_WFXPluginAdapter
 * Method:    fsLog
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_plugins_wfx_WFXPluginAdapter_fsLog
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     plugins_wfx_WFXPluginAdapter
 * Method:    fsRequest
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/StringBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_plugins_wfx_WFXPluginAdapter_fsRequest
  (JNIEnv *, jobject, jint, jint, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
